// auto-generated by scripts/build-room-region-map.py
// 入力: sakura-room の 4色 mask PNG
// 各セルは "F"(床) / "B"(奥壁) / "L"(左壁) / "R"(右壁) のいずれか。
import type { RegionCode, RoomRegionMap } from "./types.js";

export const SAKURA_ROOM_REGIONS: RoomRegionMap = {
  room: "sakura-room",
  grid: 120,
  cols: 16,
  rows: 9,
  regions: [
  ["L", "L", "L", "L", "B", "B", "B", "B", "B", "B", "B", "B", "B", "R", "R", "R"],
  ["L", "L", "L", "L", "B", "B", "B", "B", "B", "B", "B", "B", "R", "R", "R", "R"],
  ["L", "L", "L", "L", "B", "B", "B", "B", "B", "B", "B", "B", "R", "R", "R", "R"],
  ["L", "L", "L", "L", "B", "B", "B", "B", "B", "B", "B", "B", "R", "R", "R", "R"],
  ["L", "L", "L", "L", "B", "B", "B", "B", "B", "B", "B", "B", "R", "R", "R", "R"],
  ["L", "L", "L", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R", "R", "R"],
  ["L", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "R"],
  ["F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F"],
  ["F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F", "F"],
  ] as RegionCode[][],
};
