#!/usr/bin/env python3
"""
4 色マスク PNG をサンプリングして scene grid (16×9) を 4 領域に分類する。

Codex で塗ってもらった `assets/generated/<room>-mask.png`(1920×1080、
床=cyan / 奥壁=magenta / 左壁=yellow / 右壁=lime green の純色ベタ塗り)を
入力とし、各セルの中心ピクセルを色判定して JSON or TS リテラルを出力する。

使い方:
    python3 scripts/build-room-region-map.py INPUT [--out OUTPUT] [--format json|ts]

例:
    python3 scripts/build-room-region-map.py assets/generated/sakura-room-mask-20260620.png \
        --format ts --out src/editor/scene/room-regions/sakura-room.ts

出力 (json):
    {"room":"sakura-room","grid":120,"cols":16,"rows":9,
     "regions":[["L","B","B",...],["L","B","B",...],...,["F","F",...]]}
"""
import argparse, json, sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow が必要: pip install pillow", file=sys.stderr); sys.exit(2)

GRID = 120
COLS, ROWS = 16, 9

# 色 → 領域コード(1 文字)
COLORS = {
    "F": (0, 255, 255),     # floor      = cyan
    "B": (255, 0, 255),     # back-wall  = magenta
    "L": (255, 255, 0),     # left-wall  = yellow
    "R": (0, 255, 0),       # right-wall = lime green
}
CODE_LABEL = {"F":"floor", "B":"back-wall", "L":"left-wall", "R":"right-wall"}

def nearest_code(rgb):
    return min(COLORS.keys(), key=lambda k: sum((a-b)**2 for a,b in zip(rgb, COLORS[k])))

def classify(mask_path: Path):
    im = Image.open(mask_path).convert("RGB")
    W, H = im.size
    if W != COLS * GRID or H != ROWS * GRID:
        print(f"WARN: mask size {W}x{H} != {COLS*GRID}x{ROWS*GRID}", file=sys.stderr)
    regions = []
    for row in range(ROWS):
        row_arr = []
        for col in range(COLS):
            # セル中心 px をサンプル
            cx = int((col + 0.5) * GRID)
            cy = int((row + 0.5) * GRID)
            cx = min(cx, W - 1); cy = min(cy, H - 1)
            rgb = im.getpixel((cx, cy))
            row_arr.append(nearest_code(rgb))
        regions.append(row_arr)
    return regions

def rectangularize_back_wall(regions):
    """奥壁(B)を矩形に正規化する。
    透視で B が台形(上で広がる)に出てしまった場合、各 B 行の B 範囲の
    intersection (max(left) .. min(right)) を取り、その矩形外の B は
    左右どちらに近いかで L/R に振り直す。
    """
    b_rows = [r for r, row in enumerate(regions) if "B" in row]
    if not b_rows:
        return regions
    lefts = []
    rights = []
    for r in b_rows:
        row = regions[r]
        lefts.append(row.index("B"))
        rights.append(len(row) - 1 - row[::-1].index("B"))
    b_left = max(lefts)
    b_right = min(rights)
    fixed = 0
    for r in b_rows:
        for c in range(len(regions[r])):
            if regions[r][c] == "B" and not (b_left <= c <= b_right):
                regions[r][c] = "L" if c < b_left else "R"
                fixed += 1
    if fixed:
        print(f"rectangularized back wall: fixed {fixed} outlier B cell(s) → L/R", file=sys.stderr)
    return regions

def fmt_json(room_id: str, regions):
    return json.dumps({"room": room_id, "grid": GRID, "cols": COLS, "rows": ROWS,
                       "regions": regions}, ensure_ascii=False, indent=2)

def fmt_ts(room_id: str, regions):
    # TypeScript literal as a const map
    rows = ",\n  ".join("[" + ", ".join(f'"{c}"' for c in row) + "]" for row in regions)
    return f"""// auto-generated by scripts/build-room-region-map.py
// 入力: {room_id} の 4色 mask PNG
// 各セルは "F"(床) / "B"(奥壁) / "L"(左壁) / "R"(右壁) のいずれか。
import type {{ RegionCode, RoomRegionMap }} from "./types.js";

export const {room_id.replace("-", "_").upper()}_REGIONS: RoomRegionMap = {{
  room: "{room_id}",
  grid: {GRID},
  cols: {COLS},
  rows: {ROWS},
  regions: [
  {rows},
  ] as RegionCode[][],
}};
"""

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", type=Path)
    ap.add_argument("--out", type=Path, help="省略時は stdout")
    ap.add_argument("--format", choices=["json","ts"], default="json")
    ap.add_argument("--room", help="room id(省略時はファイル名から抽出)")
    ap.add_argument("--no-rectangularize", action="store_true",
                    help="奥壁(B)を矩形化しない(既定は intersection で矩形化)")
    args = ap.parse_args()

    room = args.room or args.input.stem.replace("-mask-20260620", "").replace("-mask", "")
    regions = classify(args.input)
    if not args.no_rectangularize:
        regions = rectangularize_back_wall(regions)
    out_text = fmt_ts(room, regions) if args.format == "ts" else fmt_json(room, regions)

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(out_text)
        print(f"wrote {args.out} ({sum(len(r) for r in regions)} cells)")
        # サマリ
        from collections import Counter
        c = Counter(code for row in regions for code in row)
        print("region counts:", dict((CODE_LABEL[k], v) for k,v in c.items()))
    else:
        print(out_text)

if __name__ == "__main__":
    main()
